### ISSUE TITLE
Reduce the none subword stops

### ISSUE THREAD

**Issue by arBmind** [vasama/vs-subword-navigation#1]
Very nice work using the latest async APIs for Visual Studio.

Right now the cursor jumps after the word and before the word in two steps. This feels a bit too much.

Current cursor positions with subword navigation:
```C#
    var r = new int[] { a + b };
|   |  ||||||  ||  ||||||||||||| // <- current
|   |   | | |   |  |  | | | | || // <- reduced
```

Maybe it's possible to add an option for these.
* [x] stop before subwords (always on)
* [ ] stop before whitespace (optional)
* [ ] stop between operator sequences (optional)

**Comment by vasama** [comment]
Hey, thanks for the feedback!

I've also found the current stops too dense and in fa20f9861bb1578919c2b58d96e0a128e92e9067 I've changed the default behaviour to skip whitespace after any element.

Though I designed the system with configurability in mind, I never got around to implementing an options page. Once that's all done I'll release a new version on the VS marketplace. For now you can build the extension yourself if you like.

**Comment by vasama** [comment]
New configurable version is on the VS marketplace now.
